/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.EnumerableTests;
	import flexUnitTests.FirstTests;
	import flexUnitTests.SelectTests;
	import flexUnitTests.ToArrayTests;
	import flexUnitTests.WhereTests;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var flexUnitTests_EnumerableTests_obj:flexUnitTests.EnumerableTests;
		private var flexUnitTests_WhereTests_obj:flexUnitTests.WhereTests;
		private var flexUnitTests_SelectTests_obj:flexUnitTests.SelectTests;
		private var flexUnitTests_ToArrayTests_obj:flexUnitTests.ToArrayTests;
		private var flexUnitTests_FirstTests_obj:flexUnitTests.FirstTests;
	}
}