/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flexUnitTests.WhereTests;
	
	import flash.display.Sprite;
	import flexUnitTests.ToArrayTests;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_ToArrayTests_obj:flexUnitTests.ToArrayTests;
		
		private var System_WhereTests_obj:flexUnitTests.WhereTests;
	}
}